package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 16 04:43:06 AST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class type_class_RO_VImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public type_class_RO_VImpl() {
    }
}

