package model.Entity;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 16 03:51:24 AST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FlighteoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FlightNumber,
        AirplaneId,
        Departure,
        DTime,
        Arrival,
        ATime,
        ClassInfo,
        Airplane,
        Airport,
        Airport1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int FLIGHTNUMBER = AttributesEnum.FlightNumber.index();
    public static final int AIRPLANEID = AttributesEnum.AirplaneId.index();
    public static final int DEPARTURE = AttributesEnum.Departure.index();
    public static final int DTIME = AttributesEnum.DTime.index();
    public static final int ARRIVAL = AttributesEnum.Arrival.index();
    public static final int ATIME = AttributesEnum.ATime.index();
    public static final int CLASSINFO = AttributesEnum.ClassInfo.index();
    public static final int AIRPLANE = AttributesEnum.Airplane.index();
    public static final int AIRPORT = AttributesEnum.Airport.index();
    public static final int AIRPORT1 = AttributesEnum.Airport1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FlighteoImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.Entity.Flighteo");
    }

    /**
     * Gets the attribute value for FlightNumber, using the alias name FlightNumber.
     * @return the value of FlightNumber
     */
    public String getFlightNumber() {
        return (String) getAttributeInternal(FLIGHTNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FlightNumber.
     * @param value value to set the FlightNumber
     */
    public void setFlightNumber(String value) {
        setAttributeInternal(FLIGHTNUMBER, value);
    }

    /**
     * Gets the attribute value for AirplaneId, using the alias name AirplaneId.
     * @return the value of AirplaneId
     */
    public BigDecimal getAirplaneId() {
        return (BigDecimal) getAttributeInternal(AIRPLANEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AirplaneId.
     * @param value value to set the AirplaneId
     */
    public void setAirplaneId(BigDecimal value) {
        setAttributeInternal(AIRPLANEID, value);
    }

    /**
     * Gets the attribute value for Departure, using the alias name Departure.
     * @return the value of Departure
     */
    public String getDeparture() {
        return (String) getAttributeInternal(DEPARTURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Departure.
     * @param value value to set the Departure
     */
    public void setDeparture(String value) {
        setAttributeInternal(DEPARTURE, value);
    }

    /**
     * Gets the attribute value for DTime, using the alias name DTime.
     * @return the value of DTime
     */
    public Timestamp getDTime() {
        return (Timestamp) getAttributeInternal(DTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DTime.
     * @param value value to set the DTime
     */
    public void setDTime(Timestamp value) {
        setAttributeInternal(DTIME, value);
    }

    /**
     * Gets the attribute value for Arrival, using the alias name Arrival.
     * @return the value of Arrival
     */
    public String getArrival() {
        return (String) getAttributeInternal(ARRIVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Arrival.
     * @param value value to set the Arrival
     */
    public void setArrival(String value) {
        setAttributeInternal(ARRIVAL, value);
    }

    /**
     * Gets the attribute value for ATime, using the alias name ATime.
     * @return the value of ATime
     */
    public Timestamp getATime() {
        return (Timestamp) getAttributeInternal(ATIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ATime.
     * @param value value to set the ATime
     */
    public void setATime(Timestamp value) {
        setAttributeInternal(ATIME, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getClassInfo() {
        return (RowIterator) getAttributeInternal(CLASSINFO);
    }

    /**
     * @return the associated entity AirplaneeoImpl.
     */
    public AirplaneeoImpl getAirplane() {
        return (AirplaneeoImpl) getAttributeInternal(AIRPLANE);
    }

    /**
     * Sets <code>value</code> as the associated entity AirplaneeoImpl.
     */
    public void setAirplane(AirplaneeoImpl value) {
        setAttributeInternal(AIRPLANE, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAirport() {
        return (EntityImpl) getAttributeInternal(AIRPORT);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAirport(EntityImpl value) {
        setAttributeInternal(AIRPORT, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAirport1() {
        return (EntityImpl) getAttributeInternal(AIRPORT1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAirport1(EntityImpl value) {
        setAttributeInternal(AIRPORT1, value);
    }


    /**
     * @param flightNumber key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String flightNumber) {
        return new Key(new Object[] { flightNumber });
    }

    public Number getSequenceValue(String SequenceName) {
        SequenceImpl MySeq = new SequenceImpl(SequenceName, getDBTransaction());
        return MySeq.getSequenceNumber();
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        setFlightNumber("AAQ"+getSequenceValue("FLIGHT_SEQ").toString());
    }
}

