package model.Entity;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 16 03:57:33 AST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PassangereoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        PassangerId,
        FName,
        MName,
        LName,
        Gender,
        Email,
        Cellphone,
        Booking;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PASSANGERID = AttributesEnum.PassangerId.index();
    public static final int FNAME = AttributesEnum.FName.index();
    public static final int MNAME = AttributesEnum.MName.index();
    public static final int LNAME = AttributesEnum.LName.index();
    public static final int GENDER = AttributesEnum.Gender.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int CELLPHONE = AttributesEnum.Cellphone.index();
    public static final int BOOKING = AttributesEnum.Booking.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PassangereoImpl() {
    }

    /**
     * Gets the attribute value for PassangerId, using the alias name PassangerId.
     * @return the value of PassangerId
     */
    public Number getPassangerId() {
        return (Number) getAttributeInternal(PASSANGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassangerId.
     * @param value value to set the PassangerId
     */
    public void setPassangerId(Number value) {
        setAttributeInternal(PASSANGERID, value);
    }

    /**
     * Gets the attribute value for FName, using the alias name FName.
     * @return the value of FName
     */
    public String getFName() {
        return (String) getAttributeInternal(FNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FName.
     * @param value value to set the FName
     */
    public void setFName(String value) {
        setAttributeInternal(FNAME, value);
    }

    /**
     * Gets the attribute value for MName, using the alias name MName.
     * @return the value of MName
     */
    public String getMName() {
        return (String) getAttributeInternal(MNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for MName.
     * @param value value to set the MName
     */
    public void setMName(String value) {
        setAttributeInternal(MNAME, value);
    }

    /**
     * Gets the attribute value for LName, using the alias name LName.
     * @return the value of LName
     */
    public String getLName() {
        return (String) getAttributeInternal(LNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LName.
     * @param value value to set the LName
     */
    public void setLName(String value) {
        setAttributeInternal(LNAME, value);
    }

    /**
     * Gets the attribute value for Gender, using the alias name Gender.
     * @return the value of Gender
     */
    public String getGender() {
        return (String) getAttributeInternal(GENDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for Gender.
     * @param value value to set the Gender
     */
    public void setGender(String value) {
        setAttributeInternal(GENDER, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for Cellphone, using the alias name Cellphone.
     * @return the value of Cellphone
     */
    public String getCellphone() {
        return (String) getAttributeInternal(CELLPHONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cellphone.
     * @param value value to set the Cellphone
     */
    public void setCellphone(String value) {
        setAttributeInternal(CELLPHONE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBooking() {
        return (RowIterator) getAttributeInternal(BOOKING);
    }

    /**
     * @param passangerId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number passangerId) {
        return new Key(new Object[] { passangerId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.Entity.Passangereo");
    }
    public Number getSequenceValue(String SequenceName) {
        SequenceImpl MySeq = new SequenceImpl(SequenceName, getDBTransaction());
        return MySeq.getSequenceNumber();
    }
    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        setPassangerId(getSequenceValue("PASSANGER_SEQ"));
    }
}

